export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  'Лайфхакер': 'Lifehacker',
  'Главная': 'Home',
  'Темная': 'Dark',
  'Светлая': 'Light',
  'Поиск': 'Search',
  'Войти': 'Login',
  'Выйти': 'Logout',
  'Мои инструкции': 'My instructions',
  'авторизоваться': 'authorize',
  'Случаные инструкции': 'Random instructions',
  'Облако тегов': 'Tag cloud',
  'Хотите чем-то поделиться. Нажмите': 'Have something to tell about? Click',
  'чтобы создать новую инструкцию': 'to create new instruction',
  'Добавить': 'Add',
  'Изменить': 'Edit',
  'Приветствуем в генераторе инструкций': 'Welcome to the instruction builder',
  'Заполните общую информацию': 'Fill the common info',
  'Добавьте шаги к инструкции': 'Add steps to your instruction',
  'Сохраните вашу инструкцию': 'Save your instruction',
  'Сохранить': 'Save',
  'СОХРАНИТЬ': 'SAVE',
  'Название': 'Title',
  'Категория': 'Category',
  'Описание': 'Description',
  'Теги': 'Tags',
  'Опишите вашу инструкцию': 'Describe your instruction',
  'Пока нет шагов': 'No steps yet',
  'Новый шаг': 'New step',
  'Имя': 'Name',
  'Имя шага': 'Step name',
  'Фото': 'Photo',
  'Выбрать': 'Select',
  'P.S: Можно менять порядок': 'P.S You can change the order'
};